---

#- hosts: all
#  become: true
#  pre-tasks:

#    - name: install updates (Ubuntu)
#      tags: always
#      apt:
#        update_cache: yes
#      changed_when: false
#      when: ansible_distribution == "Ubuntu"

- hosts: control_node
  become: true
  roles:
    - security_patch
    - install_docker
    - docker_suricata
